### PR TITLE
'test/unit' is not available in ruby 2.2

### PR DESCRIPTION
**Pull request by jmoody**
#### Motivation

Fixes tests for ruby 2.2.0.

See **gem is not compatible with ruby 2.2** [#6](https://github.com/cucumber/multi_test/issues/6) for details.

I am not very happy with this - I don't think it meshes well with your existing testing framework.  I will not be put-off if this is rejected.

### CODE REVIEW

**Comment by tooky** [comment]
Thanks for taking a crack at this @jmoody.

I think we should remove the `require_test_unit.rb` from the `plain_ruby` scenarios file, rather than make a special case for ruby 2.2.

In the medium term the plan is to remove the assertion library selection behaviour from multi_test and create new gems for each assertion library which will set up cucumber correctly.

@mattwynne have we felt enough pain to do this for cucumber 2.0?

**Comment by jmoody** [comment]
@tooky 

> I think we should remove the `require_test_unit.rb` from the plain_ruby scenarios file, rather than make a special case for ruby 2.2.

I was not sure if there as an action item here for me or not.

Is rescuing `LoadError` more acceptable?

**Comment by mattwynne** [comment]
@tooky I don't have the headspace to do this along with with everything else in Cucumber 2.0. If you want to handle it though, I'd be delighted.

**Comment by tooky** [comment]
@mattwynne ok I'll spend some time this evening putting together cucumber/minitest and cucumber/rspec.

This will mean the default state of cucumber is to not support any assertion library? I don't think there's any way to deprecate that in 1.3, but we can document it well as part of the cucumber 2.0 release notes?

Do you think it would be worth adding at least a method_missing catch on expect in the world to just warn people that they should include 'cucumber/rspec' in their Gemfile?

I can then pull all of the assertion library code, and associated tests out of multi_test.

**Comment by tooky** [comment]
Ref cucumber/cucumber#750

**Pull request closed without merging**
