### PR TITLE
Add Ruby 2.6 to CI.

### PR DESCRIPTION
**Pull request by junaruga**
Let's add it.

### CODE REVIEW

**Comment by olleolleolle** [comment]
@junaruga Yes! Can I merge this?

**Comment by junaruga** [comment]
@olleolleolle I want to merge this. By I lost the permission. Do you have?
I think we should merge this PR before merging other PRs.

**Comment by aslakhellesoy** [comment]
Hi @junaruga,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by junaruga** [comment]
@aslakhellesoy I know the information. I had the commit permission in the past time. When this repository started to require 2 step authorization, I lost the permission.

**Pull request merged**
